name: "AWS Create/Destroy/Sync tools"
description: "Create a new S3 Bucket ou updated thier. Or create a new Route53 entry."
author: andradedpg
runs:
  using: docker
  image: Dockerfile
branding:
  icon: refresh-cw
  color: green
